# Generated by Django 4.2 on 2023-09-22 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homepage", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Services",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256)),
                ("discriptions", models.CharField(max_length=256)),
                ("image", models.URLField(blank=True, null=True)),
                ("icon", models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
