# Generated by Django 4.2 on 2023-09-22 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("homepage", "0003_projects"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Projects",
            new_name="Project",
        ),
        migrations.RenameModel(
            old_name="Services",
            new_name="Service",
        ),
    ]
