# Generated by Django 4.2 on 2023-09-22 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("homepage", "0005_alter_project_image"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Banner",
        ),
        migrations.DeleteModel(
            name="Blurb",
        ),
    ]
