# Generated by Django 4.2 on 2023-09-22 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homepage", "0006_delete_banner_delete_blurb"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteInformation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("site_name", models.CharField(max_length=100)),
                ("site_description", models.TextField(blank=True, null=True)),
                (
                    "site_keywords",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("tagline", models.CharField(blank=True, max_length=256, null=True)),
                ("logo", models.ImageField(upload_to="uploads/")),
                ("address", models.TextField(blank=True, null=True)),
                ("telephone", models.CharField(blank=True, max_length=20, null=True)),
                ("mobile", models.CharField(blank=True, max_length=20, null=True)),
                ("fax", models.CharField(blank=True, max_length=20, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("website", models.URLField(blank=True, null=True)),
                (
                    "sales_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                (
                    "technical_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                (
                    "accounts_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                ("facebook_url", models.URLField(blank=True, null=True)),
                ("twitter_url", models.URLField(blank=True, null=True)),
                ("instagram_url", models.URLField(blank=True, null=True)),
                ("linkedin_url", models.URLField(blank=True, null=True)),
                ("about_us", models.TextField(blank=True, null=True)),
                ("privacy_policy", models.TextField(blank=True, null=True)),
                ("terms_of_service", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
