# Generated by Django 4.2 on 2023-09-22 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homepage", "0009_productcategory_product"),
    ]

    operations = [
        migrations.CreateModel(
            name="Marketing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                ("image", models.ImageField(upload_to="uploads/")),
            ],
        ),
    ]
