# Generated by Django 4.2 on 2023-09-23 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homepage", "0012_remove_testimonial_date_published"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteinformation",
            name="company_name",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
    ]
