# Generated by Django 4.2 on 2023-09-23 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homepage", "0013_siteinformation_company_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="marketing",
            name="action",
            field=models.CharField(default="", max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="marketing",
            name="action_url",
            field=models.URLField(default=""),
            preserve_default=False,
        ),
    ]
