# Generated by Django 4.2 on 2023-09-23 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homepage", "0015_feature"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feature",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="feature/"),
        ),
        migrations.AlterField(
            model_name="service",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="service/"),
        ),
    ]
