# Generated by Django 4.2 on 2023-09-23 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homepage", "0017_alter_feature_discriptions_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="discriptions",
            field=models.TextField(),
        ),
    ]
