# Generated by Django 4.2 on 2023-09-23 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("homepage", "0018_alter_project_discriptions"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="serices",
        ),
        migrations.AddField(
            model_name="project",
            name="category",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="services",
                to="homepage.category",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="productcategory",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="products/"),
        ),
    ]
