# Generated by Django 4.2 on 2023-09-23 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homepage", "0020_alter_project_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="client",
            field=models.CharField(default="", max_length=256),
            preserve_default=False,
        ),
    ]
