# Generated by Django 4.2 on 2023-09-23 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homepage", "0022_alter_project_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="category",
        ),
        migrations.AddField(
            model_name="project",
            name="category",
            field=models.ManyToManyField(to="homepage.category"),
        ),
    ]
