# Generated by Django 4.2 on 2023-09-24 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homepage", "0024_remove_project_category_project_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="file",
            field=models.FileField(default="", upload_to=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="project",
            name="is_published",
            field=models.BooleanField(default=False),
        ),
    ]
