# Generated by Django 4.2 on 2023-09-25 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homepage", "0026_project_created_at_project_updated_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=30)),
                ("subject", models.CharField(max_length=250)),
                ("message", models.TextField()),
            ],
        ),
    ]
