# Generated by Django 4.2 on 2023-09-25 21:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("homepage", "0027_contact"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="action",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="contact",
            name="submission_date",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
